# Apache httpd serving a static page.
# Note the docroot differs from nginx: httpd uses /usr/local/apache2/htdocs.
FROM httpd:2.4-alpine

COPY index.html /usr/local/apache2/htdocs/index.html

EXPOSE 80
