apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s20-gitops
resources:
  - ../../base
  - legacy-config.yaml
replicas:
  - name: podinfo
    count: 2
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.9.1
