apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s20-gitops
resources:
  - ../../base
replicas:
  - name: podinfo
    count: 3
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.9.2
