# Same pod with the default ClusterFirst policy -> uses CoreDNS from the kubelet
apiVersion: v1
kind: Pod
metadata:
  namespace: s14-t2-client
  name: dns-bad
spec:
  dnsPolicy: ClusterFirst
  containers:
    - name: client
      image: registry.k8s.io/e2e-test-images/agnhost:2.39
      command: ["sleep", "3600"]
      resources:
        requests: {cpu: 10m, memory: 16Mi}
