apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: s20-monitoring-demo
  labels:
    release: monitoring          # matches the kube-prometheus-stack release name
spec:
  selector:
    matchLabels: { app: podinfo }
  endpoints:
    - port: http                 # the Service port NAME
      path: /metrics
      interval: 15s
