apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: final-app
labels:
  - pairs: { app.kubernetes.io/part-of: final-devops-project }
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
