apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: podinfo
      app.kubernetes.io/part-of: s20-gitops
resources:
  - deployment.yaml
  - service.yaml
