apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/netram75/devops-heros
    targetRevision: session21-gitops
    path: session21-python/final-devops-project/gitops/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: final-app
  syncPolicy:
    automated:
      prune: true      # delete objects that were removed from Git
      selfHeal: true   # undo manual changes made with kubectl
    syncOptions:
      - CreateNamespace=true
