apiVersion: v1
kind: Secret
metadata:
  name: {{ include "final-app.fullname" . }}-secret
  labels:
    {{- include "final-app.labels" . | nindent 4 }}
type: Opaque
data:
  API_TOKEN: {{ required "secret.apiToken is required" .Values.secret.apiToken | b64enc | quote }}
