apiVersion: v1
kind: Service
metadata:
  name: release-checklist
  namespace: session17
  labels:
    app.kubernetes.io/name: release-checklist
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: release-checklist
  ports:
    - name: http
      port: 80
      targetPort: http
