apiVersion: v1
kind: PersistentVolume
metadata:
  name: s13-local-pv
spec:
  storageClassName: s13-local-wffc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/s13-local-pv
    type: DirectoryOrCreate
